FROM python:3.9

ENV PYTHONUNBUFFERED 1

WORKDIR /api

COPY . /api/.

RUN rm -rf /api/venv
RUN rm -rf /api/frontend

RUN python -m pip install --upgrade pip

RUN pip install -r  requirements.txt --no-cache

EXPOSE 8000

CMD ["make", "run_app"]
